apiVersion: v1
kind: Service
metadata:
  name: reactjs-app-service
  namespace: default
  labels:
    app: reactjs-app
spec:
  selector:
    app: reactjs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer